FROM docker-registry.guokr.com/guokr/python27
MAINTAINER Patrick Kennedy <patkennedy79@gmail.com>
LABEL Description="WeChat Group Robot API" Vendor="Guokr wo zui zai hang Group" Version="1.2"


RUN apt-get update \
 	&& apt-get install -y nano wget dialog net-tools \
	&& apt-get install -y gunicorn \
	&& apt-get install -y supervisor

# Create the working directory (and set it as the working directory)
RUN mkdir -p /app/
COPY . /app/
WORKDIR /app/

# Install the package dependencies (this step is separated
# from copying all the source code to avoid having to
# re-install all python packages defined in requirements.txt
# whenever any source code change is made)
RUN pip install --upgrade pip -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
RUN pip install -r requirements.txt -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com

EXPOSE 80
